name: 'elmah.io Upload Source Map Action'
author: 'elmah.io'
description: 'GitHub Action to upload a source map on elmah.io'
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  apiKey:
    description: 'An API key with permission to upload source maps.'
    required: true
  logId:
    description: 'The ID of the log which should contain the minified JavaScript and source map.'
    required: true
  path:
    description: 'An URL to the online minified JavaScript file. The URL can be absolute or relative but will always be converted to a relative path (no protocol, domain, and query parameters). elmah.io uses this path to lookup any lines in a JS stack trace that will need de-minification.'
    required: true
  sourceMap:
    description: 'A path to the source map file. Only files with an extension of .map and content type of application/json will be accepted.'
    required: true
  minifiedJavaScript:
    description: 'A path to the minified JavaScript file. Only files with an extension of .js and content type of text/javascript will be accepted.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.apiKey }}
    - ${{ inputs.logId }}
    - ${{ inputs.path }}
    - ${{ inputs.sourceMap }}
    - ${{ inputs.minifiedJavaScript }}